config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  post 'login' => 'sessions#login'
  post 'logout' => 'sessions#logout'

  resources :comments
  resources :tags
  resources :answers
  resources :records
  resources :users

end

app/models/record.rb
class Record < ActiveRecord::Base
	belongs_to :user
	has_many :comments
	has_many :tags
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  before_action :set_record, only: [:show, :edit, :update, :destroy]

  # GET /records
  # GET /records.json
  def index
    @records = Record.all
    @current_user_login = current_user_login
  end

  # GET /records/1
  # GET /records/1.json
  def show
    @record = Record.find(params["id"])
    @current_user_id = current_user_id
  end

  # GET /records/new
  def new
    @record = Record.new
  end

  # GET /records/1/edit
  def edit
  end

  # POST /records
  # POST /records.json
  def create
    @record = Record.new(record_params)
    @record.user = current_user_id
    respond_to do |format|
      if @record.save
        format.html { redirect_to @record, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @record }
      else
        format.html { render :new }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records/1
  # PATCH/PUT /records/1.json
  def update
    respond_to do |format|
      if @record.update(record_params)
        format.html { redirect_to @record, notice: 'Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @record }
      else
        format.html { render :edit }
        format.json { render json: @record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records/1
  # DELETE /records/1.json
  def destroy
    @record.destroy
    respond_to do |format|
      format.html { redirect_to records_url, notice: 'Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_record
      @record = Record.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def record_params
      params.require(:record).permit(:theme,:body)
    end
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/views/records/_form.html.erb
<%= form_for(@record) do |f| %>
  <% if @record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@record.errors.count, "error") %> prohibited this record from being saved:</h2>

      <ul>
      <% @record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions panel panel-success">
    <div class="panel-heading">
      <%= label_tag(:theme, "Theme:") %>
      <%= f.text_field :theme, :class => 'form-control'%>
    </div>
    <div class="panel-body">
      <%= label_tag(:body, "Body:") %>
      <%= f.text_area :body, :class => 'form-control'%>
    </div>
    <div class="row">
      <div class="col-sm-10">
        <%= link_to 'Back', records_path, :class => 'btn btn-danger'%>
      </div>
      <div class="col-sm-2">
        <%= f.submit :class => 'btn btn-primary'%>
      </div>
    </div>
  </div>
<% end %>

app/views/records/edit.html.erb
<h1>Editing Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @record %> |
<%= link_to 'Back', records_path %>

app/views/records/index.html.erb
<%= render 'templates/navbar' %>

<p id="notice"><%= notice %></p>
<div class="row page-header">
  <div class="col-sm-6 text-center">
    <h1>Listing Records</h1>
  </div>
  <div class="col-sm-4 text-right">
    <% if @current_user_login%>
      <%= link_to 'New Record', new_record_path, :class => 'btn btn-primary' %>
    <%end%>
  </div>
</div>

<div class="row">
  <div class="col-sm-2">

  </div>
  <div class="col-sm-8">
      <% @records.each do |record| %>
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3><%= record.theme %></h3>
          </div>
          <div class="panel-body">
            <%= record.body %>            
          </div>
          <div>
            <div class="row">
              <div class="col-sm-1">Pэ
                <%= record.rating %>                
              </div>
              <div class="col-sm-8">
                <%= link_to 'Show', record %>
              </div>
              <div class="col-sm-2">
                Author: <%= record.user_id %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
  <div class="col-sm-2">

  </div>
</div>

app/views/records/new.html.erb
<%= render 'templates/navbar' %>
<h1>New Record</h1>

<%= render 'form' %>

app/views/records/show.html.erb
<%= render 'templates/navbar' %>
<p id="notice"><%= notice %></p>

<div class="row">
  <a href="/records">
    <div class="col-sm-2 btn btn-default">
      All records
    </div>
  </a>
  <div class="col-sm-8">
        <div class="panel panel-primary">
          <div class="panel-heading">
            <h3><%= @record.theme %></h3>
          </div>
          <div class="panel-body">
            <%= @record.body %>            
          </div>
          <div>
            <div class="row">
              <div class="col-sm-1">Pэ
                <%= @record.rating %>                
              </div>
              <div class="col-sm-8">
             	<%if @record.user_id == @current_user_id%>
	                <%= link_to 'Edit', edit_record_path(@record) %>
	                <%= link_to 'Destroy', @record, method: :delete, data: { confirm: 'Are you sure?' } %>
                <%end%>
              </div>
              <div class="col-sm-2">
                Author: <%= @record.user_id %>
              </div>
            </div>
          </div>
        </div>
  </div>
  <div class="col-sm-2">

  </div>
</div>